language: node_js
node_js:
  - 14
addons:
  packages:
  - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - eslint 'src/**'
  - yarn test:coveralls
notifications:
  email: false