export { default as PatrimonyList } from './patrimony-list/patrimony-list'
export { default as PatrimonyCreate } from './patrimony-create/patrimony-create'
export { default as PatrimonyUpdate } from './patrimony-update/patrimony-update'
export { default as SignUp } from './signup/signup'
export { default as Login } from './login/login'
export { default as SectorList } from './sector-list/sector-list'
export { default as SectorCreate } from './sector-create/sector-create'
