export * from './add-patrimony'
export * from './delete-patrimony'
export * from './load-patrimonies'
export * from './load-patrimonies-by-category-id'
export * from './load-patrimonies-by-owner-id'
export * from './load-patrimony-by-id'
export * from './load-patrimony-by-number'
export * from './update-patrimony'
